### ISSUE TITLE
TUI: recurring --startuptime output from both processes

### ISSUE THREAD

**Issue by dstein64** [neovim/neovim#23036]
### Problem

The output when using `--startuptime` includes two blocks of data.

I noticed this when using Neovim 0.9 with a plugin I wrote that reports startuptime measurements, [vim-startuptime](https://github.com/dstein64/vim-startuptime).

### Steps to reproduce

```
# first remove any existing startuptime output (assumed file tmpfile), otherwise the startuptime
# output is appended to the existing file.
rm tmpfile

nvim --clean --startuptime tmpfile
:quit
```

This results in two blocks of data in `tmpfile` (I replaced some of the output with `...`). The numbers in the second block do not match the first, and also the second block has less lines than the first.

```

times in msec
 clock   self+sourced   self:  sourced script
 clock   elapsed:              other lines

000.004  000.004: --- NVIM STARTING ---
000.091  000.087: event init
000.168  000.077: early init
000.211  000.043: locale set
000.252  000.041: init first window
000.469  000.217: inits 1
000.483  000.014: window checked
000.487  000.004: parsing arguments
000.812  000.038  000.038: require('vim.shared')
000.885  000.027  000.027: require('vim._meta')
000.887  000.072  000.046: require('vim._editor')
000.888  000.147  000.037: require('vim._init_packages')
...
012.380  000.002: editing files in windows
012.440  000.060: VimEnter autocommands
012.442  000.002: UIEnter autocommands
012.443  000.001: before starting main loop
013.327  000.885: first screen update
013.329  000.001: --- NVIM STARTED ---


times in msec
 clock   self+sourced   self:  sourced script
 clock   elapsed:              other lines

000.006  000.006: --- NVIM STARTING ---
009.772  009.766: event init
017.254  007.482: early init
017.296  000.042: locale set
021.391  004.095: init first window
027.266  005.875: inits 1
027.273  000.007: window checked
027.276  000.003: parsing arguments
031.589  000.031  000.031: require('vim.shared')
031.668  000.034  000.034: require('vim._meta')
031.669  000.077  000.043: require('vim._editor')
031.670  000.141  000.033: require('vim._init_packages')
031.673  004.255: init lua interpreter
032.279  000.606: expanding arguments
032.307  000.028: inits 2
032.544  000.237: init highlight
```

### Expected behavior

I expected a single block of data:

```
times in msec
 clock   self+sourced   self:  sourced script
 clock   elapsed:              other lines

000.004  000.004: --- NVIM STARTING ---
000.091  000.087: event init
000.168  000.077: early init
000.211  000.043: locale set
000.252  000.041: init first window
000.469  000.217: inits 1
000.483  000.014: window checked
000.487  000.004: parsing arguments
000.812  000.038  000.038: require('vim.shared')
000.885  000.027  000.027: require('vim._meta')
000.887  000.072  000.046: require('vim._editor')
000.888  000.147  000.037: require('vim._init_packages')
...
012.380  000.002: editing files in windows
012.440  000.060: VimEnter autocommands
012.442  000.002: UIEnter autocommands
012.443  000.001: before starting main loop
013.327  000.885: first screen update
013.329  000.001: --- NVIM STARTED ---
```

### Neovim version (nvim -v)

NVIM v0.9.0

### Vim (not Nvim) behaves the same?

No (9.0.242)

### Operating system/version

Kubuntu 22.10

### Terminal name/version

Konsole 22.08.2

### $TERM environment variable

xterm-256color

### Installation

appimage

**Comment by dstein64** [comment]
`git bisect` shows that this started at one of the following commits:
2448816
43e8ec9

I had to skip checking the first due to the following build error:
```
src/nvim/tui/tui.c:1262: undefined reference to `show_verbose_terminfo'
```

Cc: @bfredl

**Comment by bfredl** [comment]
yep, we need to integrate the output from the TUI process with the main process somehow.

**Comment by pabloariasal** [comment]
First and foremost we should ensure that each process writes to its own file. The way this is implemented today we have two processes that simultaneously write their times to the same file. It may look more or less well formatted but that's just because the TUI process happens to flush only until the process is stopped (i.e. when nvim is closed). You can verify this by inspecting the startuptimes file while nvim is still running. We can achieve this by including the pid in the filename, for exampl, or by creating two files: filename.tui and filename.main.

Once we have both files we must merge them into a single report, IMO a concatenation is probably acceptable:

```
-- TUI Process --
(Startup times of TUI process)

-- Main Process --
(Startup times of Main process)
```
We can try to merge the times of both processes into a single timeline but that is challeging as they don't start at the same time.

@bfredl what do you think?
