### PR TITLE
cmake: Linux: define _GNU_SOURCE.

### LINKED ISSUE #4042: ‘O_NOFOLLOW’ undeclared (first use in this function)
When pulling from master I get the following build error

```
/users/gbrown/src/binstrap/src/neovim/src/nvim/fileio.c: In function ‘buf_write’:
/users/gbrown/src/binstrap/src/neovim/src/nvim/fileio.c:2719: error: ‘O_NOFOLLOW’ undeclared (first use in this function)
/users/gbrown/src/binstrap/src/neovim/src/nvim/fileio.c:2719: error: (Each undeclared identifier is reported only once
/users/gbrown/src/binstrap/src/neovim/src/nvim/fileio.c:2719: error: for each function it appears in.)
/users/gbrown/src/binstrap/src/neovim/src/nvim/fileio.c: In function ‘vim_rename’:
/users/gbrown/src/binstrap/src/neovim/src/nvim/fileio.c:4569: error: ‘O_NOFOLLOW’ undeclared (first use in this function)
make[4]: *** [src/nvim/CMakeFiles/nvim.dir/fileio.c.o] Error 1
```

This appears to have been introduced by commit 07265d221fbd3b4fd16440caab49c70d14370079.

Not sure why this hasn't broken the build, I'm guessing this is because I am on
an ancient SLES box.

Platform details

```
$ uname -a
Linux cflcs01 3.0.101-0.47.71-default #1 SMP Thu Nov 12 12:22:22 UTC 2015 (b5b212e) x86_64 x86_64 x86_64 GNU/Linux

$ rpm -qif /usr/include/fcntl.h
Name        : glibc-devel                  Relocations: (not relocatable)
Version     : 2.11.3                            Vendor: SUSE LINUX Products GmbH, Nuernberg, Germany
Release     : 17.90.4                       Build Date: Thu 08 Oct 2015 01:15:31 PM CDT
Install Date: Sat 21 Nov 2015 09:54:50 AM CST      Build Host: sheep11
Group       : Development/Libraries/C and C++   Source RPM: glibc-2.11.3-17.90.4.src.rpm
Size        : 32759081                         License: BSD 3-Clause; GPL v2 or later; LGPL v2.1 or later
Signature   : RSA/8, Wed 14 Oct 2015 01:45:40 PM CDT, Key ID e3a5c360307e3d54
Packager    : https://www.suse.com/
URL         : http://www.gnu.org/software/libc/libc.html
Summary     : Include Files and Libraries Mandatory for Development
Description :
These libraries are needed to develop programs which use the standard C
library.
Distribution: SUSE Linux Enterprise 11
```

Build info

```
$ gcc --version
gcc (SUSE Linux) 4.3.4 [gcc-4_3-branch revision 152973]
Copyright (C) 2008 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

$ cmake --version
cmake version 3.4.20160116

CMake suite maintained and supported by Kitware (kitware.com/cmake).
```

### PR DESCRIPTION
**Pull request by justinmk**
Closes #4042

cc @george-b @Pyrohh @sethjackson @jszakmeister

### CODE REVIEW

**Comment by Pyrohh** [comment]
Tentative OK from me; I wanted to avoid this because it'll pull in a lot of function declarations we don't use, but that's not that big a deal... is it?

**Comment by sethjackson** [comment]
LGTM provided we don't care about pulling in extra `glibc` garbage.

**Comment by george-b** [comment]
I can confirm this allows me to build out of the box on the crappy SLES system referenced in #4042 thanks!

**Comment by justinmk** [comment]
Going to wait until 0.1.2 is released before merging this.
