### PR TITLE
fix(build): remove amalg build target for LuaJIT

### LINKED ISSUE #16172: Build failure on LuaJIT with parallel build
### Neovim version (nvim -v)

head

### Vim (not Nvim) behaves the same?

n/a

### Operating system/version

ubuntu 20.04 (via WSL)

### Terminal name/version

n/a

### $TERM environment variable

n/a

### Installation

n/a

### How to reproduce the issue

make CMAKE_BUILD_TYPE=RelWithDebInfo CMAKE_INSTALL_PREFIX=/home/dch/.local/nvim -j8

### Expected behavior

compiles

### Actual behavior

Many errors, starting like this:

```
/usr/bin/ld: libluajit.a(ljamalg.o): in function `lj_err_throw':
/home/dch/neovim/.deps/build/src/luajit/src/lj_err.c:735: multiple definition of `lj_err_throw'; libluajit.a(lj_err.o):/home/dch/neovim/.deps/build/src/luajit/src/lj_err.c:735: first defined here
/usr/bin/ld: libluajit.a(ljamalg.o): in function `lua_atpanic':
/home/dch/neovim/.deps/build/src/luajit/src/lj_err.c:1052: multiple definition of `lua_atpanic'; libluajit.a(lj_err.o):/home/dch/neovim/.deps/build/src/luajit/src/lj_err.c:1052: first defined here
/usr/bin/ld: libluajit.a(ljamalg.o): in function `lj_func_closeuv':
/home/dch/neovim/.deps/build/src/luajit/src/lj_func.c:84: multiple definition of `lj_func_closeuv'; libluajit.a(lj_func.o):/home/dch/neovim/.deps/build/src/luajit/src/lj_func.c:84: first defined here
/usr/bin/ld: libluajit.a(ljamalg.o): in function `lua_setlocal':
/home/dch/neovim/.deps/build/src/luajit/src/lj_debug.c:420: multiple definition of `lua_setlocal'; libluajit.a(lj_debug.o):/home/dch/neovim/.deps/build/src/luajit/src/lj_debug.c:420: first defined here
/usr/bin/ld: libluajit.a(ljamalg.o): in function `lua_getstack':
/home/dch/neovim/.deps/build/src/luajit/src/lj_debug.c:538: multiple definition of `lua_getstack'; libluajit.a(lj_debug.o):/home/dch/neovim/.deps/build/src/luajit/src/lj_debug.c:538: first defined here
/usr/bin/ld: libluajit.a(ljamalg.o): in function `lj_state_growstack':
/home/dch/neovim/.deps/build/src/luajit/src/lj_state.c:104: multiple definition of `lj_state_growstack'; libluajit.a(lj_state.o):/home/dch/neovim/.deps/build/src/luajit/src/lj_state.c:104: first defined here
/usr/bin/ld: libluajit.a(ljamalg.o): in function `lj_str_new':
/home/dch/neovim/.deps/build/src/luajit/src/lj_str.c:315: multiple definition of `lj_str_new'; libluajit.a(lj_str.o):/home/dch/neovim/.deps/build/src/luajit/src/lj_str.c:315: first defined here
/usr/bin/ld: libluajit.a(ljamalg.o): in function `luaL_where':
/home/dch/neovim/.deps/build/src/luajit/src/lj_err.c:1078: multiple definition of `luaL_where'; libluajit.a(lj_err.o):/home/dch/neovim/.deps/build/src/luajit/src/lj_err.c:1078: first defined here
/usr/bin/ld: libluajit.a(ljamalg.o):(.data.rel.local+0x0): multiple definition of `lj_err_allmsg'; libluajit.a(lj_err.o):(.data.rel.local+0x0): first defined here
/usr/bin/ld: libluajit.a(ljamalg.o): in function `lj_err_trace':
/home/dch/neovim/.deps/build/src/luajit/src/lj_err.c:856: multiple definition of `lj_err_trace'; libluajit.a(lj_err.o):/home/dch/neovim/.deps/build/src/luajit/src/lj_err.c:856: first defined here
/usr/bin/ld: libluajit.a(ljamalg.o): in function `lua_error':
/home/dch/neovim/.deps/build/src/luajit/src/lj_err.c:1060: multiple definition of `lua_error'; libluajit.a(lj_err.o):/home/dch/neovim/.deps/build/src/luajit/src/lj_err.c:1060: first defined here
/usr/bin/ld: libluajit.a(ljamalg.o): in function `luaL_argerror':
/home/dch/neovim/.deps/build/src/luajit/src/lj_err.c:1066: multiple definition of `luaL_argerror'; libluajit.a(lj_err.o):/home/dch/neovim/.deps/build/src/luajit/src/lj_err.c:1066: first defined here
/usr/bin/ld: libluajit.a(ljamalg.o):(.data.rel.ro.local+0x10e0): multiple definition of `lj_obj_itypename'; libluajit.a(lj_obj.o):(.data.rel.ro.local+0x0): first defined here
/usr/bin/ld: libluajit.a(ljamalg.o): in function `luaL_typerror':
/home/dch/neovim/.deps/build/src/luajit/src/lj_err.c:1072: multiple definition of `luaL_typerror'; libluajit.a(lj_err.o):/home/dch/neovim/.deps/build/src/luajit/src/lj_err.c:1072: first defined here
/usr/bin/ld: libluajit.a(ljamalg.o):(.data.rel.ro.local+0x1160): multiple definition of `lj_obj_typename'; libluajit.a(lj_obj.o):(.data.rel.ro.local+0x80): f
...
```

git bisect says that 6acfbd810d31e8c2771a475388568925dc90d141 is the first commit where this fails

### PR DESCRIPTION
**Pull request by clason**
fixup for #16041 (`amalg` build is recommended by LuaJIT for performance
but this way of doing it breaks parallel build with `make -j`)

closes #16172 

(This change was part of the experimental PR and shouldn't have made it into the final commit; *mea culpa*!)

### CODE REVIEW

**Comment by clason** [comment]
I still think switching to an `amalg` build is worth it, but someone more familiar with CMake needs to look into separating the `build` and `install` steps for LuaJIT.
