### ISSUE TITLE
Build failure in OS X Yosemite - gcc 4.9

### ISSUE THREAD

**Issue by elmart** [neovim/neovim#1980]
When trying to compile with gcc 4.9 on OS X Yosemite, I get this:

```
[ 42%] Performing build step for 'libuv'
  CC       src/libuv_la-fs-poll.lo
  CC       src/libuv_la-inet.lo
  CC       src/libuv_la-threadpool.lo
In file included from /usr/include/dispatch/dispatch.h:51:0,
                 from /System/Library/Frameworks/CoreFoundation.framework/Headers/CFStream.h:15,
                 from /System/Library/Frameworks/CoreFoundation.framework/Headers/CFPropertyList.h:13,
                 from /System/Library/Frameworks/CoreFoundation.framework/Headers/CoreFoundation.h:55,
                 from /System/Library/Frameworks/CoreServices.framework/Headers/CoreServices.h:19,
                 from /Users/eliseo/projects/os/neovim/neovim/.deps/build/src/libuv/src/unix/internal.h:52,
                 from /Users/eliseo/projects/os/neovim/neovim/.deps/build/src/libuv/src/threadpool.c:25:
/usr/include/dispatch/object.h:143:15: error: expected identifier or '(' before '^' token
 typedef void (^dispatch_block_t)(void);
               ^
/usr/include/dispatch/object.h:362:3: error: unknown type name 'dispatch_block_t'
   dispatch_block_t notification_block);
   ^
make[5]: *** [src/libuv_la-threadpool.lo] Error 1
make[4]: *** [build/src/libuv-stamp/libuv-build] Error 2
make[3]: *** [CMakeFiles/libuv.dir/all] Error 2
make[2]: *** [all] Error 2
make[1]: *** [deps] Error 2
make: *** [rebuild] Error 2
```

**Comment by timfeirg** [comment]
I'm on OS X yosemite 10.10.2 (14C109), with latest gcc (4.9.2) from brew, I occasionally encounter build errors like this:

```
==> make CMAKE_BUILD_TYPE=RelWithDebInfo CMAKE_EXTRA_FLAGS="-DCMAKE_INSTALL_PREFIX:PATH=/usr/local/Cellar/neovim/HEAD" install

make[3]: *** [usr/bin/busted] Error 1
make[2]: *** [CMakeFiles/busted.dir/all] Error 2
make[1]: *** [all] Error 2
make: *** [deps] Error 2
```

But if I re-run `brew reinstall --HEAD neovim`, it'd always pass at the second or third try, I don't understand any of these but perhaps you could try the latest version of brewed gcc? with a clean build environment (check with `brew doctor`)?

**Comment by justinmk** [comment]
Code has changed a lot in that area. Haven't had any similar reports.
