### ISSUE TITLE
compilation error with MSVC on windows 10 with :terminal

### ISSUE THREAD

**Issue by grimgort** [neovim/neovim#15065]
with nvim 5.0, i have this error when i compile my code on windows 10 :
![image](https://user-images.githubusercontent.com/44238325/125264829-81ae7300-e304-11eb-85c7-dafb79b8d7af.png)

**Comment by grimgort** [comment]
Working with release 5.0 . i close this issue
