### ISSUE TITLE
Neovim 0.11.5 fails to build with tree-sitter 0.26

### ISSUE THREAD

**Issue by vdcow** [neovim/neovim#36914]
### Problem

Neovim 0.11.5 fails to build with the new release of tree-sitter (0.26)
```
/usr/src/RPM/BUILD/neovim-0.11.5/src/nvim/lua/treesitter.c: In function 'parser_parse':
/usr/src/RPM/BUILD/neovim-0.11.5/src/nvim/lua/treesitter.c:541:9: error: implicit declaration of function 'ts_parser_timeout_mic
ros' [-Wimplicit-function-declaration]
  541 |     if (ts_parser_timeout_micros(p) == 0) {
      |         ^~~~~~~~~~~~~~~~~~~~~~~~
/usr/src/RPM/BUILD/neovim-0.11.5/src/nvim/lua/treesitter.c: In function 'parser_set_timeout':
/usr/src/RPM/BUILD/neovim-0.11.5/src/nvim/lua/treesitter.c:683:3: error: implicit declaration of function 'ts_parser_set_timeout
_micros'; did you mean 'parser_set_timeout'? [-Wimplicit-function-declaration]
  683 |   ts_parser_set_timeout_micros(p, timeout);
      |   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |   parser_set_timeout
gmake[2]: *** [src/nvim/CMakeFiles/nvim_bin.dir/build.make:6059: src/nvim/CMakeFiles/nvim_bin.dir/lua/treesitter.c.o] Error 1
```
It looks like this issue is fixed in master but do we expect this issue to be fixed in Neovim 0.11?

### Steps to reproduce

```
cmake -DCMAKE_POLICY_VERSION_MINIMUM=3.5 -DCMAKE_SKIP_INSTALL_RPATH:BOOL=yes '-DCMAKE_C_FLAGS:STRING=-pipe -frecord-gcc-switch
es -Wall -g -O2 -flto=auto' '-DCMAKE_CXX_FLAGS:STRING=-pipe -frecord-gcc-switches -Wall -g -O2 -flto=auto' '-DCMAKE_Fortran_FLAG
S:STRING=-pipe -frecord-gcc-switches -Wall -g -O2 -flto=auto' -DCMAKE_INSTALL_PREFIX=/usr -DINCLUDE_INSTALL_DIR:PATH=/usr/includ
e -DLIB_INSTALL_DIR:PATH=/usr/lib64 -DSYSCONF_INSTALL_DIR:PATH=/etc -DSHARE_INSTALL_PREFIX:PATH=/usr/share -DLIB_DESTINATION=lib
64 -DLIB_SUFFIX=64 -S . -B x86_64-alt-linux -DCMAKE_BUILD_TYPE=RelWithDebInfo -DNVIM_VERSION_RELEASE=alt1 -D USE_BUNDLED=OFF
```

### Expected behavior

Neovim should support build with tree-sitter 0.26

### Nvim version (nvim -v)

0.11.5

### Vim (not Nvim) behaves the same?

N/A

### Operating system/version

Alt Linux Sisyphus

### Terminal name/version

N/A

### $TERM environment variable

N/A

### Installation

Doing RPM package build

**Comment by clason** [comment]
Neovim 0.11.5 is intended to build with 0.25.x and is not compatible with 0.26 (while for 0.12/nightly it is the other way around). 

As a zerover project, minor version bumps have to be assumed to be breaking.
