### ISSUE TITLE
mark_tree.c check_node method used before definition cause compilation error on MSVC toolchain

### ISSUE THREAD

**Issue by mvphilip** [neovim/neovim#13663]
This is a compilation issue when using MSVC/14.28.29617 . In src/nvim/mark_tree.c the function:

void marktree_check(MarkTree *b)

is using the function check_node. But check_node is not defined at this point. Its in fact the next function definition. The order of definition should be reversed.

In MSVC/14.28.29617 as the initial symbol is undefined it builds a dummy definition and then gives an error as its later redefined:

\marktree.c(1106,28): warning C4013: 'check_node' undefined; assuming extern returning int 
marktree.c(1116,15): error C2371: 'check_node': redefinition; different basic types

This compiles fine with g++ 10 but even so this seems bad practice.

I can submit a PR with the order reversed but this seems straightforward.

thanks,

-mp

**Comment by jamessan** [comment]
Our build process auto-generates header files that declare all the static functions to avoid having to micro-manage this sort of thing.  For marktree.c, you can see it being included here:

https://github.com/neovim/neovim/blob/48caf1df8581a9a9da9072f901411b918333952d/src/nvim/marktree.c#L105-L107

It sounds like either `INCLUDE_GENERATED_DECLARATIONS` is somehow not being defined for you or the header file doesn't have the declaration.

**Comment by mvphilip** [comment]
Thanks for the quick feedback. Let me debug then. This was the only error in the build so its curious why. I will re-open this issue when I have some findings.

thanks,

-mp
