### ISSUE TITLE
RelWithDebInfo build "error: inlining failed"

### ISSUE THREAD

**Issue by justinmk** [neovim/neovim#3071]
Build error (gcc (Ubuntu 4.8.4-2ubuntu1~14.04) 4.8.4) caused by 7732bec9b8b94cb43647dcb7f5bd2619224bd87a.

```
make[3]: Entering directory `/home/ubuntu/neovim/build'
[  9%] Building C object src/nvim/CMakeFiles/nvim.dir/__/__/config/auto/pathdef.c.o
[  9%] Building C object src/nvim/CMakeFiles/nvim.dir/auto/msgpack_dispatch.c.o
[  9%] Building C object src/nvim/CMakeFiles/nvim.dir/eval.c.o
In file included from /usr/include/features.h:374:0,
                 from /usr/include/assert.h:35,
                 from /home/ubuntu/neovim/src/nvim/eval.c:14:
/home/ubuntu/neovim/src/nvim/eval.c: In function ‘f_ceil’:
/usr/include/i386-linux-gnu/bits/mathinline.h:761:1: error: inlining failed in call to always_inline ‘ceil’: indirect function call with a yet undetermined callee
 __inline_mathcodeNP (ceil, __x, \
 ^
/home/ubuntu/neovim/src/nvim/eval.c:7112:35: error: called from here
     rettv->vval.v_float = function(f);
                                   ^
In file included from /usr/include/features.h:374:0,
                 from /usr/include/assert.h:35,
                 from /home/ubuntu/neovim/src/nvim/eval.c:14:
/home/ubuntu/neovim/src/nvim/eval.c: In function ‘f_floor’:
/usr/include/i386-linux-gnu/bits/mathinline.h:743:1: error: inlining failed in call to always_inline ‘floor’: indirect function call with a yet undetermined callee
 __inline_mathcodeNP (floor, __x, \
 ^
/home/ubuntu/neovim/src/nvim/eval.c:7112:35: error: called from here
     rettv->vval.v_float = function(f);
                                   ^
```

This may be breaking the homebrew build as well: https://github.com/neovim/neovim/issues/3070#issuecomment-123399395

cc @wandernauta

**Comment by wandernauta** [comment]
Interesting. I'm on GCC 5.1.0 64 bit, so that might have something to do with it. Will submit a PR to make `float_op_wrapper` not inline.

**Comment by wandernauta** [comment]
Tried this with Ubuntu 14.04, GCC 4.8.4, libc 2.19-0ubuntu6.6, RelWithDebInfo, 64-bit, and I can't reproduce: it seems to compile and runs fine.

I'll check to see if there's a way to get GCC 4.8.4 32-bit running on this machine.

**Comment by justinmk** [comment]
Yeah this is a 32-bit VM. Did you `rm -rf build/` before compiling (to make sure cmake wasn't using a cached "Debug" config)?

**Comment by wandernauta** [comment]
Ah, I think I found it. I *can* reproduce the problem in master with 32-bit libc (compiling with `-m32`), so it appears to be a 32-bit specific optimization inside libc. The fix in #3072 seems to work.
