### ISSUE TITLE
Build failure on LuaJIT with parallel build

### ISSUE THREAD

**Issue by dimbleby** [neovim/neovim#16172]
### Neovim version (nvim -v)

head

### Vim (not Nvim) behaves the same?

n/a

### Operating system/version

ubuntu 20.04 (via WSL)

### Terminal name/version

n/a

### $TERM environment variable

n/a

### Installation

n/a

### How to reproduce the issue

make CMAKE_BUILD_TYPE=RelWithDebInfo CMAKE_INSTALL_PREFIX=/home/dch/.local/nvim -j8

### Expected behavior

compiles

### Actual behavior

Many errors, starting like this:

```
/usr/bin/ld: libluajit.a(ljamalg.o): in function `lj_err_throw':
/home/dch/neovim/.deps/build/src/luajit/src/lj_err.c:735: multiple definition of `lj_err_throw'; libluajit.a(lj_err.o):/home/dch/neovim/.deps/build/src/luajit/src/lj_err.c:735: first defined here
/usr/bin/ld: libluajit.a(ljamalg.o): in function `lua_atpanic':
/home/dch/neovim/.deps/build/src/luajit/src/lj_err.c:1052: multiple definition of `lua_atpanic'; libluajit.a(lj_err.o):/home/dch/neovim/.deps/build/src/luajit/src/lj_err.c:1052: first defined here
/usr/bin/ld: libluajit.a(ljamalg.o): in function `lj_func_closeuv':
/home/dch/neovim/.deps/build/src/luajit/src/lj_func.c:84: multiple definition of `lj_func_closeuv'; libluajit.a(lj_func.o):/home/dch/neovim/.deps/build/src/luajit/src/lj_func.c:84: first defined here
/usr/bin/ld: libluajit.a(ljamalg.o): in function `lua_setlocal':
/home/dch/neovim/.deps/build/src/luajit/src/lj_debug.c:420: multiple definition of `lua_setlocal'; libluajit.a(lj_debug.o):/home/dch/neovim/.deps/build/src/luajit/src/lj_debug.c:420: first defined here
/usr/bin/ld: libluajit.a(ljamalg.o): in function `lua_getstack':
/home/dch/neovim/.deps/build/src/luajit/src/lj_debug.c:538: multiple definition of `lua_getstack'; libluajit.a(lj_debug.o):/home/dch/neovim/.deps/build/src/luajit/src/lj_debug.c:538: first defined here
/usr/bin/ld: libluajit.a(ljamalg.o): in function `lj_state_growstack':
/home/dch/neovim/.deps/build/src/luajit/src/lj_state.c:104: multiple definition of `lj_state_growstack'; libluajit.a(lj_state.o):/home/dch/neovim/.deps/build/src/luajit/src/lj_state.c:104: first defined here
/usr/bin/ld: libluajit.a(ljamalg.o): in function `lj_str_new':
/home/dch/neovim/.deps/build/src/luajit/src/lj_str.c:315: multiple definition of `lj_str_new'; libluajit.a(lj_str.o):/home/dch/neovim/.deps/build/src/luajit/src/lj_str.c:315: first defined here
/usr/bin/ld: libluajit.a(ljamalg.o): in function `luaL_where':
/home/dch/neovim/.deps/build/src/luajit/src/lj_err.c:1078: multiple definition of `luaL_where'; libluajit.a(lj_err.o):/home/dch/neovim/.deps/build/src/luajit/src/lj_err.c:1078: first defined here
/usr/bin/ld: libluajit.a(ljamalg.o):(.data.rel.local+0x0): multiple definition of `lj_err_allmsg'; libluajit.a(lj_err.o):(.data.rel.local+0x0): first defined here
/usr/bin/ld: libluajit.a(ljamalg.o): in function `lj_err_trace':
/home/dch/neovim/.deps/build/src/luajit/src/lj_err.c:856: multiple definition of `lj_err_trace'; libluajit.a(lj_err.o):/home/dch/neovim/.deps/build/src/luajit/src/lj_err.c:856: first defined here
/usr/bin/ld: libluajit.a(ljamalg.o): in function `lua_error':
/home/dch/neovim/.deps/build/src/luajit/src/lj_err.c:1060: multiple definition of `lua_error'; libluajit.a(lj_err.o):/home/dch/neovim/.deps/build/src/luajit/src/lj_err.c:1060: first defined here
/usr/bin/ld: libluajit.a(ljamalg.o): in function `luaL_argerror':
/home/dch/neovim/.deps/build/src/luajit/src/lj_err.c:1066: multiple definition of `luaL_argerror'; libluajit.a(lj_err.o):/home/dch/neovim/.deps/build/src/luajit/src/lj_err.c:1066: first defined here
/usr/bin/ld: libluajit.a(ljamalg.o):(.data.rel.ro.local+0x10e0): multiple definition of `lj_obj_itypename'; libluajit.a(lj_obj.o):(.data.rel.ro.local+0x0): first defined here
/usr/bin/ld: libluajit.a(ljamalg.o): in function `luaL_typerror':
/home/dch/neovim/.deps/build/src/luajit/src/lj_err.c:1072: multiple definition of `luaL_typerror'; libluajit.a(lj_err.o):/home/dch/neovim/.deps/build/src/luajit/src/lj_err.c:1072: first defined here
/usr/bin/ld: libluajit.a(ljamalg.o):(.data.rel.ro.local+0x1160): multiple definition of `lj_obj_typename'; libluajit.a(lj_obj.o):(.data.rel.ro.local+0x80): f
...
```

git bisect says that 6acfbd810d31e8c2771a475388568925dc90d141 is the first commit where this fails

**Comment by justinmk** [comment]
did you try `rm -rf .deps` or `make distclean` ?

**Comment by mystilleef** [comment]
> did you try `rm -rf .deps` or `make distclean` ?

Yes, still doesn't compile.

**Comment by ristillu** [comment]
I am also getting the same errors as @dimbleby. I also `rm -rf .deps` and `make distclean` but the errors persist.

**Comment by ristillu** [comment]
I suspect I have a quick and dirty fix: I failed compilation several times with `make CMAKE_BUILD_TYPE=RelWithDebInfo -j 10` but have succeeded now twice without multiple parallel jobs, i.e. just running `make CMAKE_BUILD_TYPE=RelWithDebInfo`

**Comment by zeertzjq** [comment]
Build also fails in MINGW_64-gcov and MINGW_32 tests, which may be related.

**Comment by mjlbach** [comment]
Maybe try reverting https://github.com/neovim/neovim/commit/6acfbd810d31e8c2771a475388568925dc90d141?

**Comment by clason** [comment]
MingW tests are not related; that's something to do with runner environment.

It's weird that it doesn't build for you, since it built for Ubuntu on CI. Maybe some more build flags are needed?

**Comment by clason** [comment]
Can you try cloning the LuaJIT repo and building with `make`? Does that work for you?

**Comment by clason** [comment]
And, lastly, do you have `ninja` installed?

**Comment by clason** [comment]
I suspect that this has to do with this line: https://github.com/neovim/neovim/blob/e921e98ce38a33a824a8b4efb376a9901a8191d7/third-party/cmake/BuildLuajit.cmake#L61

LuaJIT recommends `amalg` builds for performance, but apparently this doesn't play nice with parallel builds via `make -j`. Note that it seems to work fine both for me and CI when using `ninja`, which is a recommended build dependency -- do you have that installed? 

1. if not, could you install it and try again?
2. if yes, could you try removing the `amalg` from the line above and try again?

**Comment by mystilleef** [comment]
Following @clason suggestion, using `-j1` instead of `-j4` fixes this issue for me.

**Comment by clason** [comment]
That's nice, but that wasn't actually my suggestion :)

**Comment by mystilleef** [comment]
> That's nice, but that wasn't actually my suggestion :)

I think the issue is related to parallel builds, not the other stuff. I have `ninja` installed, not `amalg`. The short-term solution seems to be not to compile in parallel.

**Comment by clason** [comment]
OK, if you have `ninja` installed, you should _not_ be using `make -j`.

`amalg` is not a tool but a build target -- can you change the line 61 in `third-party/cmake/BuildLuajit.cmake` to just `install)` (remove the `amalg`)?

**Comment by clason** [comment]
Please try #16178

**Comment by mystilleef** [comment]
@clason It built successfully after remove `amalg` regardless of the `-j` flags I used.
