### ISSUE TITLE
`gf` Command Unable to Navigate to File and Line Number Correctly in Neovim v0.9.1 on Windows

### ISSUE THREAD

**Issue by aenichols** [neovim/neovim#25160]
### Problem

The gf command in Neovim is not behaving as expected when trying to navigate to a file and a specific line number. The function grab_file_name appears to have some issue with parsing both the file name and the line number.

For instance, when trying to go to a file and line number using gf on the following line,

``` bash
Error: src/app/core/services/identity/identity.service.ts:64:23 - error TS2551: Property 'tfaSmsEn
dClientClientOptOutAllowed' does not exist on type 'FullLoginResponse'. Did you mean 'endClientCli
I get the error E447: Can't find file
```

I get the error E447: Can't find file "src/app/core/services/identity/identity.service.ts:64:23". Even isolating the text does not help. This issue also persists in visual and block selection modes.

### Steps to reproduce

1. Open a buffer with a line that contains a file path and line number like so:
    `src/app/core/services/identity/identity.service.ts:64`
2. Try using the gf command to navigate to the file and specific line number.

Note: The issue seems consistent across multiple files and line numbers.

### Expected behavior

I expect the gf command to navigate to the specific file and line number mentioned in the text.

### Neovim version (nvim -v)

NVIM v0.9.1

### Vim (not Nvim) behaves the same?

yes, vim 9.0.1403

### Operating system/version

Windows 11 Pro 22H2

### Terminal name/version

GNU bash, version 5.2.15(1)-release (x86_64-pc-msys)

### $TERM environment variable

xterm-256color

### Installation

Installed using Scoop on Windows.

**Comment by llllvvuu** [comment]
Data point: working fine on 0.9.2 on MacOS

Does it reproduce on a blank buffer? (no file)

**Comment by lsvmello** [comment]
This is a Windows specific "issue". Vim also has this problem.
The problem is that on Windows the trailing colon (:) are not ignored, so Neovim (and vim) tries to find a file named *identity.service.ts:64*.

The colon (:) is not ignored because Windows hard drive partition (e.g.: **C:\\** or **D:\\**).

I thinks it's possible to fix that with a not so clean solution or the `:help gf` should be fixed to point this behavior on Windows.

**Comment by llllvvuu** [comment]
Drive is max one letter right? IDK if that's a viable solution though

**Comment by zeertzjq** [comment]
`:set isfname-=:` should work, but it's a global option and and doing that will cause drive letter not to be recognized as a part of file name as well.

**Comment by justinmk** [comment]
> The colon (:) is not ignored because Windows hard drive partition (e.g.: **C:\** or **D:\**).

Whatever logic is doing that definitely needs to be fixed. If a colon occurs _after_ a slash (and after skipping any "scheme" segment such as `file:/`), it should not be treated as a drive letter.

**Comment by lsvmello** [comment]
> `:set isfname-=:` should work, but it's a global option and and doing that will cause drive letter not to be recognized as a part of file name as well.

`set isfname+=:` on linux/mac emulates the problem that happens on Windows.

---
I have done some tests:

| path |  `gf` on Windows | `gf` on Linux |
|-------|--------------------|---------------|
| file.txt | file.txt | file.txt |
| file.txt:22:7 | **file.txt:22:7** | file.txt |
| /file.txt | /file.txt | /file.txt |
| /file.txt:22:7 | **/file.txt:22:7** | /file.txt |
| C:/temp/file.txt | C:/temp/file.txt | **C:/temp/file.txt** |
| C:/temp/file.txt:22:7 | **C:/temp/file.txt:22:7** | **C:/temp/file.txt:22:7** |
| file://C:/temp/file.txt | C:/temp/file.txt | **C:/temp/file.txt** |
| file://C:/temp/file.txt:22:7 | **C:/temp/file.txt:22:7** | **C:/temp/file.txt:22:7** |
| http://localhost:8080/ | http://localhost:8080/ | http://localhost:8080/ |
| http://localhost:3000/path | http://localhost:3000/path | http://localhost:3000/path |

_FYI.: **netrw** was on_

Even without the colon on the `isfname` linux sometimes considers the colon.

If we always considers colon as part of the path we can add logic to jump to line and column (e.g.: _<file_path>_**:**_<line_number>_**:**_<column_number>_).

**Comment by aenichols** [comment]
> `:set isfname-=:` should work, but it's a global option and and doing that will cause drive letter not to be recognized as a part of file name as well.

This does work work but does not go to the line number.

**Comment by justinmk** [comment]
> This does work but does not go to the line number.

Use `gF` (not `gf`) for that.

**Comment by Daydreamer-riri** [comment]
Hi @justinmk, 我在 0.10.1 上仍然存在这个问题：
![image](https://github.com/user-attachments/assets/99f3164e-e130-49a0-a806-57edf1c84f72)
