### ISSUE TITLE
Neovim won't build on OS X 10.6.8 (using Homebrew)

### ISSUE THREAD

**Issue by msravi** [neovim/neovim#3021]
This is the error that is thrown:

```
Undefined symbols:
  "_libiconv_close", referenced from:
      _readfile in fileio.c.o
      _readfile in fileio.c.o
      _readfile in fileio.c.o
      _buf_write in fileio.c.o
      _my_iconv_open in mbyte.c.o
      _convert_setup_ext in mbyte.c.o
  "_libiconv", referenced from:
      _readfile in fileio.c.o
      _buf_write_bytes in fileio.c.o
      _buf_write_bytes in fileio.c.o
      _my_iconv_open in mbyte.c.o
      _string_convert_ext in mbyte.c.o
  "_libiconv_open", referenced from:
      _my_iconv_open in mbyte.c.o
ld: symbol(s) not found
collect2: ld returned 1 exit status
make[3]: *** [bin/nvim] Error 1
make[2]: *** [src/nvim/CMakeFiles/nvim.dir/all] Error 2
make[1]: *** [all] Error 2
make: *** [nvim] Error 2
==> Formula
Tap: neovim/homebrew-neovim
Path: /usr/local/Library/Taps/neovim/homebrew-neovim/Formula/neovim.rb
==> Configuration
HOMEBREW_VERSION: 0.9.5
ORIGIN: https://github.com/Homebrew/homebrew
HEAD: 836afe0685334784d8766ce2f4709e2f87089551
Last commit: 26 minutes ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CELLAR: /usr/local/Cellar
HOMEBREW_BOTTLE_DOMAIN: https://homebrew.bintray.com
CPU: quad-core 64-bit arrandale
OS X: 10.6.8-i386
Xcode: 3.2.6
CLT: N/A
GCC-4.0: build 5494
GCC-4.2: build 5666
LLVM-GCC: build 2335
Clang: 1.7 build 77
X11: 2.3.6 => /usr/X11
System Ruby: 1.8.7-p358
Perl: /usr/bin/perl
Python: /Library/Frameworks/Python.framework/Versions/2.7/bin/python => /Library/Frameworks/Python.framework/Versions/2.7/bin/python2.7
Ruby: /Users/msravi/.rbenv/shims/ruby => /System/Library/Frameworks/Ruby.framework/Versions/1.8/usr/bin/ruby
Java: 1.6.0_65
==> ENV
HOMEBREW_CC: gcc-4.2
HOMEBREW_CXX: g++-4.2
CMAKE_PREFIX_PATH: /usr/local/opt/libtool:/usr/local/opt/automake:/usr/local/opt/autoconf:/usr/local/opt/gettext:/usr/local
CMAKE_INCLUDE_PATH: /usr/include/libxml2:/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers
CMAKE_LIBRARY_PATH: /System/Library/Frameworks/OpenGL.framework/Versions/Current/Libraries
PKG_CONFIG_LIBDIR: /usr/lib/pkgconfig:/usr/local/Library/ENV/pkgconfig/10.6
ACLOCAL_PATH: /usr/local/opt/libtool/share/aclocal:/usr/local/opt/automake/share/aclocal:/usr/local/opt/gettext/share/aclocal:/usr/local/share/aclocal
PATH: /Library/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS:/usr/local/Library/ENV/4.3:/usr/local/opt/cmake/bin:/usr/local/opt/libtool/bin:/usr/local/opt/automake/bin:/usr/local/opt/autoconf/bin:/usr/local/opt/pkg-config/bin:/usr/local/opt/gettext/bin:/usr/bin:/bin:/usr/sbin:/sbin

Error: neovim/neovim/neovim HEAD did not build
```
Edit: Updated with more info from the log

**Comment by mhinz** [comment]
https://github.com/neovim/homebrew-neovim/issues/26

Does this help?

**Comment by msravi** [comment]
Thank you, it sure did!

I don't have macports or fink installed (and no /sw or /opt/local folder). I've run with verbose turned on and there aren't any links to /sw or /opt/local. However, the workaround suggested by @jakerr worked like a charm. This should probably be documented somewhere...

Thanks, again.
