### ISSUE TITLE
nvim via flake in contrib/flake.nix broken, master and nightly

### ISSUE THREAD

**Issue by BirdeeHub** [neovim/neovim#28861]
### Problem

The flake in the repo has become broken due to something with treesitter

This also affects the [neovim-nightly-overlay](https://github.com/nix-community/neovim-nightly-overlay)

```nix build github:neovim/neovim/nightly?dir=contrib``` fails.

```nix build github:neovim/neovim?dir=contrib``` fails.

```nix build nixpkgs#neovim``` succeeds, it has probably not recieved whatever update is the issue.

When built as a part of my config as an input it gives this error:

```
       … while evaluating derivation 'neovim-unwrapped-62eb7e7'
         whose name attribute is located at /nix/store/cyd4dmjf4in4hyf6ink75a2lbf7fqp7z-source/pkgs/stdenv/generic/make-derivation.nix:331:7

       … while evaluating attribute 'preConfigure' of derivation 'neovim-unwrapped-62eb7e7'

         at /nix/store/2ya2fn4q61v8qmcz1144jcvsimzzwz9a-source/contrib/flake.nix:62:11:

           61|           src = ../.;
           62|           preConfigure = oa.preConfigure or "" + ''
             |           ^
           63|             sed -i cmake.config/versiondef.h.in -e 's/@NVIM_VERSION_PRERELEASE@/-dev-${version}/'

       … while calling anonymous lambda

         at /nix/store/cyd4dmjf4in4hyf6ink75a2lbf7fqp7z-source/lib/attrsets.nix:1096:10:

         1095|     attrs:
         1096|     map (name: f name attrs.${name}) (attrNames attrs);
             |          ^
         1097|

       … from call site

         at /nix/store/cyd4dmjf4in4hyf6ink75a2lbf7fqp7z-source/lib/attrsets.nix:1096:16:

         1095|     attrs:
         1096|     map (name: f name attrs.${name}) (attrNames attrs);
             |                ^
         1097|

       … while calling anonymous lambda

         at /nix/store/cyd4dmjf4in4hyf6ink75a2lbf7fqp7z-source/pkgs/by-name/ne/neovim-unwrapped/package.nix:176:18:

          175|     '' + lib.concatStrings (lib.mapAttrsToList
          176|       (language: grammar: ''
             |                  ^
          177|         ln -s \

       … while evaluating derivation 'bash-grammar-neovim-62eb7e7'
         whose name attribute is located at /nix/store/cyd4dmjf4in4hyf6ink75a2lbf7fqp7z-source/pkgs/stdenv/generic/make-derivation.nix:331:7

       … while evaluating attribute 'src' of derivation 'bash-grammar-neovim-62eb7e7'

         at /nix/store/cyd4dmjf4in4hyf6ink75a2lbf7fqp7z-source/pkgs/by-name/ne/neovim-unwrapped/package.nix:179:30:

          178|           ${tree-sitter.buildGrammar {
          179|             inherit (grammar) src;
             |                              ^
          180|             version = "neovim-${finalAttrs.version}";

       error: attribute 'src' missing

       at /nix/store/cyd4dmjf4in4hyf6ink75a2lbf7fqp7z-source/pkgs/by-name/ne/neovim-unwrapped/package.nix:178:39:

          177|         ln -s \
          178|           ${tree-sitter.buildGrammar {
             |                                       ^
          179|             inherit (grammar) src;
       Did you mean url?
```

### and when built on its own

with the command ```nix build github:neovim/neovim/nightly?dir=contrib```

I get a log with the interesting parts being:

```
CMake Warning:
  Manually-specified variables were not used by the project:

    BUILD_TESTING
    CMAKE_CXX_COMPILER
    CMAKE_EXPORT_NO_PACKAGE_REGISTRY
    CMAKE_POLICY_DEFAULT_CMP0025
    USE_BUNDLED


-- Build files have been written to: /build/k0kxjaa76zlwflxv9c63g1pjakl0ikcr-source/build
cmake: enabled parallel building
cmake: enabled parallel installing
@nix { "action": "setPhase", "phase": "buildPhase" }
Running phase: buildPhase
build flags: -j8 SHELL=/nix/store/a1s263pmsci9zykm5xcdf7x9rv26w6d5-bash-5.2p26/bin/bash
```
### And

```
/build/k0kxjaa76zlwflxv9c63g1pjakl0ikcr-source/src/nvim/lua/treesitter.c: In function '__has_ancestor':
[ 70%] Building C object src/nvim/CMakeFiles/nvim_bin.dir/main.c.o
/build/k0kxjaa76zlwflxv9c63g1pjakl0ikcr-source/src/nvim/lua/treesitter.c:1084:12: warning: implicit declaration of function 'ts_node_child_containing_descendant'; did you mean 'node_child_containing_descendant'? >
 1084 |     node = ts_node_child_containing_descendant(node, descendant);
      |            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |            node_child_containing_descendant
/build/k0kxjaa76zlwflxv9c63g1pjakl0ikcr-source/src/nvim/lua/treesitter.c:1084:12: error: incompatible types when assigning to type 'TSNode' from type 'int'
/build/k0kxjaa76zlwflxv9c63g1pjakl0ikcr-source/src/nvim/lua/treesitter.c: In function 'node_child_containing_descendant':
/build/k0kxjaa76zlwflxv9c63g1pjakl0ikcr-source/src/nvim/lua/treesitter.c:1095:18: error: invalid initializer
 1095 |   TSNode child = ts_node_child_containing_descendant(node, descendant);
      |                  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[ 70%] Building C object src/nvim/CMakeFiles/nvim_bin.dir/map.c.o
make[2]: *** [src/nvim/CMakeFiles/nvim_bin.dir/build.make:3430: src/nvim/CMakeFiles/nvim_bin.dir/lua/treesitter.c.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[1]: *** [CMakeFiles/Makefile2:623: src/nvim/CMakeFiles/nvim_bin.dir/all] Error 2
make: *** [Makefile:156: all] Error 2
```

### Steps to reproduce

```nix build github:neovim/neovim/nightly?dir=contrib```

OR

```
    neovim-flake = {
      url = "github:neovim/neovim/nightly?dir=contrib";
      # optional, happens either way: inputs.nixpkgs.follows = "nixpkgs";
      # optional, happens either way: inputs.flake-utils.follows = "flake-utils";
    };

```

### Expected behavior

I expected it to build.

### Neovim version (nvim -v)

nightly tag

### Vim (not Nvim) behaves the same?

N/A

### Operating system/version

nixos

### Terminal name/version

alacritty

### $TERM environment variable

xterm-256color

### Installation

flake in contrib folder of repo

**Comment by clason** [comment]
Duplicate; the contrib flake is in the process of being moved out of this repo.

**Comment by BirdeeHub** [comment]
Where is it being moved to?

**Comment by clason** [comment]
https://github.com/nix-community/neovim-nightly-overlay/pull/483

**Comment by BirdeeHub** [comment]
Thank you :)
