### ISSUE TITLE
Build failure with clang-3.4.1

### ISSUE THREAD

**Issue by yurivict** [neovim/neovim#4750]
- Neovim version:0.1.4
- Operating system/version: FreeBSD 10
- Terminal name/version:
- `$TERM`:

fails to build with clang-3.4.1:

```
/usr/ports/editors/neovim/work/neovim-0.1.4/src/nvim/shada.c:3232:32: warning: type specifier missing, defaults to 'int' [-Wimplicit-int]
static inline uint64_t be64toh(uint64_t big_endian_64_bits)
                       ~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/include/sys/endian.h:77:29: note: expanded from macro 'be64toh'
#define be64toh(x)      bswap64((x))
                                 ^
/usr/include/sys/endian.h:61:30: note: expanded from macro 'bswap64'
#define bswap64(x)      __bswap64(x)
                                  ^
/usr/include/x86/endian.h:80:24: note: expanded from macro '__bswap64'
        (__builtin_constant_p(x) ?      \
                              ^
/usr/ports/editors/neovim/work/neovim-0.1.4/src/nvim/shada.c:3232:24: error: expected ')'
static inline uint64_t be64toh(uint64_t big_endian_64_bits)
                       ^
/usr/include/sys/endian.h:77:20: note: expanded from macro 'be64toh'
#define be64toh(x)      bswap64((x))
                        ^
/usr/include/sys/endian.h:61:20: note: expanded from macro 'bswap64'
#define bswap64(x)      __bswap64(x)
                        ^
/usr/include/x86/endian.h:80:27: note: expanded from macro '__bswap64'
        (__builtin_constant_p(x) ?      \
                                 ^
/usr/ports/editors/neovim/work/neovim-0.1.4/src/nvim/shada.c:3232:24: note: to match this '('
/usr/include/sys/endian.h:77:20: note: expanded from macro 'be64toh'
#define be64toh(x)      bswap64((x))
                        ^
/usr/include/sys/endian.h:61:20: note: expanded from macro 'bswap64'
#define bswap64(x)      __bswap64(x)
                        ^
/usr/include/x86/endian.h:80:2: note: expanded from macro '__bswap64'
        (__builtin_constant_p(x) ?      \
        ^
/usr/ports/editors/neovim/work/neovim-0.1.4/src/nvim/shada.c:3232:24: error: static declaration of '__builtin_constant_p' follows non-static declaration
static inline uint64_t be64toh(uint64_t big_endian_64_bits)
                       ^
/usr/include/sys/endian.h:77:20: note: expanded from macro 'be64toh'
#define be64toh(x)      bswap64((x))
                        ^
/usr/include/sys/endian.h:61:20: note: expanded from macro 'bswap64'
#define bswap64(x)      __bswap64(x)
                        ^
/usr/include/x86/endian.h:80:3: note: expanded from macro '__bswap64'
        (__builtin_constant_p(x) ?      \
         ^
/usr/local/include/msgpack/pack_template.h:280:20: note: previous implicit declaration is here
    buf[0] = 0xcd; _msgpack_store16(&buf[1], d);
                   ^
/usr/local/include/msgpack/sysdep.h:156:25: note: expanded from macro '_msgpack_store16'
    do { uint16_t val = _msgpack_be16(num); memcpy(to, &val, 2); } while(0)
                        ^
/usr/local/include/msgpack/sysdep.h:94:34: note: expanded from macro '_msgpack_be16'
#        define _msgpack_be16(x) ntohs(x)
                                 ^
/usr/include/arpa/inet.h:173:18: note: expanded from macro 'ntohs'
#define ntohs(x)        __ntohs(x)
                        ^
/usr/include/x86/endian.h:129:20: note: expanded from macro '__ntohs'
#define __ntohs(x)      __bswap16(x)
                        ^
/usr/include/x86/endian.h:74:16: note: expanded from macro '__bswap16'
        ((__uint16_t)(__builtin_constant_p(x) ? \
                      ^
/usr/ports/editors/neovim/work/neovim-0.1.4/src/nvim/shada.c:3232:24: error: definition of builtin function '__builtin_constant_p'
static inline uint64_t be64toh(uint64_t big_endian_64_bits)
                       ^
/usr/include/sys/endian.h:77:20: note: expanded from macro 'be64toh'
#define be64toh(x)      bswap64((x))
                        ^
/usr/include/sys/endian.h:61:20: note: expanded from macro 'bswap64'
#define bswap64(x)      __bswap64(x)
                        ^
/usr/include/x86/endian.h:80:3: note: expanded from macro '__bswap64'
        (__builtin_constant_p(x) ?      \
         ^
/usr/ports/editors/neovim/work/neovim-0.1.4/src/nvim/shada.c:3232:32: error: parameter name omitted
static inline uint64_t be64toh(uint64_t big_endian_64_bits)
                               ^
/usr/include/sys/endian.h:77:29: note: expanded from macro 'be64toh'
#define be64toh(x)      bswap64((x))
                                 ^
/usr/include/sys/endian.h:61:30: note: expanded from macro 'bswap64'
#define bswap64(x)      __bswap64(x)
                                  ^
/usr/include/x86/endian.h:80:24: note: expanded from macro '__bswap64'
        (__builtin_constant_p(x) ?      \
                              ^
/usr/ports/editors/neovim/work/neovim-0.1.4/src/nvim/shada.c:3240:31: error: use of undeclared identifier 'big_endian_64_bits'
  uint8_t *buf = (uint8_t *) &big_endian_64_bits;
                              ^
1 warning and 5 errors generated.
ninja: build stopped: subcommand failed.
===> Compilation failed unexpectedly.
Try to set MAKE_JOBS_UNSAFE=yes and rebuild before reporting the failure to
the maintainer.
*** Error code 1

Stop.
make: stopped in /usr/ports/editors/neovim
```

**Comment by jszakmeister** [comment]
I'm not building through ports, but Neovim 0.1.4 builds just find on my FreeBSD 10 box with Clang 3.4.1.

**Comment by yurivict** [comment]
I hit the failure in port since that's how people normally install it.

**Comment by jszakmeister** [comment]
> I hit the failure in port since that's how people normally install it.

I understand that, but since the issue happens in the port install and not using a source build, it raises the possibility that the port is at fault and not Neovim.

So, there are a few interesting things here.  It appears that FreeBSD actually has the be64toh() macros, but no `endian.h`--they're actually in `sys/endian.h`.  Because of that, HAVE_BE64TOH is being set to false, and we're including shada's version of the function.  The problem is that sys/endian.h has been included somewhere along the way, and our function name is now being replaced by the macro, creating an illegal definition.

I think I have a fix for this, but that won't fix the port install.  They (the FreeBSD maintainer for the port) will likely need to backport my fix.
