### ISSUE TITLE
error: expected expression (related to __attribute__((fallthrough)))

### ISSUE THREAD

**Issue by ryandesign** [neovim/neovim#10125]
- `nvim --version`: 0.3.7
- Vim (version: ) behaves differently? n/a
- Operating system/version: OS X 10.9.5
- Terminal name/version: n/a
- `$TERM`: n/a

### Steps to reproduce using `nvim -u NORC`

Run cmake and then make

### Actual behaviour

Build failure. First there are many warnings of this type:

```
./src/nvim/buffer.c:3736:7: warning: declaration does not declare anything [-Wmissing-declarations]
      FALLTHROUGH;
      ^~~~~~~~~~~
./src/nvim/macros.h:169:22: note: expanded from macro 'FALLTHROUGH'
# define FALLTHROUGH __attribute__((fallthrough))
                     ^~~~~~~~~~~~~
```

Then there is an error:

```
./src/nvim/regexp_nfa.c:3263:7: error: expected expression
      FALLTHROUGH;
      ^
./src/nvim/macros.h:169:22: note: expanded from macro 'FALLTHROUGH'
# define FALLTHROUGH __attribute__((fallthrough))
                     ^
```

It builds fine on OS X 10.10 and later. I assume this fallthrough attribute is something that isn't supported by the older compilers found on 10.9 and earlier.

### Expected behaviour

Successful build

**Comment by justinmk** [comment]
but we already check for compiler support: https://github.com/neovim/neovim/blob/4f92354326ae149eda60e0ee61e3a7cc2421530b/src/nvim/macros.h#L168

what `clang --version` ?

see also 5ec72aadbf51a729969cb7f9f06cf573fc77da59

**Comment by ryandesign** [comment]
Here's the full [build failure log](https://build.macports.org/builders/ports-10.9_x86_64-builder/builds/90360/steps/install-port/logs/stdio). The compiler is Apple LLVM version 6.0 (clang-600.0.57) (based on LLVM 3.5svn), from Xcode 6.2, the last version for OS X 10.9.

**Comment by justinmk** [comment]
Hard to decipher that "clang version" , but I guess `LLVM 3.5svn` could suggest clang 3.5. Try changing this line to `NVIM_HAS_ATTRIBUTE 0`: https://github.com/neovim/neovim/blob/4f92354326ae149eda60e0ee61e3a7cc2421530b/src/nvim/macros.h#L165

Also would be good if you could print the value of `__clang_major__` and `__clang_minor__`.

Seems like a version mixup, maybe apple reported the wrong version number or we need to adjust the version check in that macro.

**Comment by ryandesign** [comment]
```
$ /usr/bin/clang  -dM -E - < /dev/null | grep __clang_m
#define __clang_major__ 6
#define __clang_minor__ 0
```

Apple LLVM/Clang version numbers differ from open source LLVM/Clang version numbers. You might need to use `__apple_build_version__`:

```
$ /usr/bin/clang  -dM -E - < /dev/null | grep __apple
#define __apple_build_version__ 6000057
```

Here's how it looks on OS X 10.10, where the build succeeds:

```
$ /usr/bin/clang  -dM -E - < /dev/null|grep -E '__(apple|clang_m)'
#define __apple_build_version__ 7000181
#define __clang_major__ 7
#define __clang_minor__ 0
```

So, if `__apple_build_version__` is defined and is less than `7000000` then don't use fallthrough.

**Comment by justinmk** [comment]
Can you send a PR?
