### ISSUE TITLE
Can't build neovim from git using paru (AUR manager)

### ISSUE THREAD

**Issue by syntezoid** [neovim/neovim#14926]
- `nvim --version`: NVIM v0.5.0-dev+1450-g5aaa1a1c0
Build type: RelWithDebInfo
LuaJIT 2.0.5
Compilation: /usr/lib/ccache/bin/cc -march=native -mtune=native -O3 -pipe -fno-plt -fexceptions     -Wp,-D_FORTIFY_SOURCE=2 -Wformat -Werror=format-security     -fstack-clash-protection -fcf-protection -flto -Wp,-U_FORTIFY_SOURCE -Wp,-D_FORTIFY_SOURCE=1 -O2 -g -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/home/roland/.cache/paru/clone/neovim-git/src/build/config -I/home/roland/.cache/paru/clone/neovim-git/src/neovim-git/src -I/usr/include -I/home/roland/.cache/paru/clone/neovim-git/src/build/src/nvim/auto -I/home/roland/.cache/paru/clone/neovim-git/src/build/include
Compiled by roland

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"

Run :checkhealth for more info
- Operating system/version: Arch linux
- Terminal name/version: Alacritty 0.8
- `$TERM`: Alacritty

[ ] `vim -u DEFAULTS` (version: ) behaves differently

### Steps to reproduce using `nvim -u NORC`

```
nvim -u NORC
# Alternative for shell-related problems:
# env -i TERM=ansi-256color "$(which nvim)"

```

### Actual behaviour
When I try to build neovim from git using AUR package neovim-git it failing with this:
```
[100%] Linking C executable ../../bin/nvim
/usr/bin/ld: /usr/bin/ld: DWARF error: invalid abstract instance DIE ref
/tmp/cco52kjV.ltrans23.ltrans.o: in function `node_rawquery':
<artificial>:(.text+0x1d21): undefined reference to `ts_query_cursor_set_match_limit'
collect2: error: ld returned 1 exit status
make[2]: *** [src/nvim/CMakeFiles/nvim.dir/build.make:3658: bin/nvim] Error 1
make[1]: *** [CMakeFiles/Makefile2:2806: src/nvim/CMakeFiles/nvim.dir/all] Error 2
make: *** [Makefile:156: all] Error 2
==> ERROR: A failure occurred in build().
    Aborting...
error: failed to build 'neovim-git-0.4.0.r2972.g3fbff98cf-1':
checking dependencies...
```
### Expected behaviour
It should compile without problem, as before.

**Comment by tomcur** [comment]
The same error occurs when trying to build it using Nix:

```
~ % nix build 'github:neovim/neovim?dir=contrib'
...
       > /nix/store/rqfgki7ck1bxqhk3hd7wziqhahjadfbj-binutils-2.35.1/bin/ld: /build/nvim.sbH30E.ltrans27.ltrans.o: in function `node_rawquery':
       > <artificial>:(.text+0x11d8): undefined reference to `ts_query_cursor_set_match_limit'
       > collect2: error: ld returned 1 exit status
       > make[2]: *** [src/nvim/CMakeFiles/nvim.dir/build.make:3525: bin/nvim] Error 1
       > make[1]: *** [CMakeFiles/Makefile2:3027: src/nvim/CMakeFiles/nvim.dir/all] Error 2
       > make: *** [Makefile:171: all] Error 2
       For full logs, run 'nix log /nix/store/j9yq6vm9k2j8avmkpk8qyvg6j7s8wc7s-neovim-unwrapped-master.drv'.
```

**Comment by tomcur** [comment]
This issue is introduced in 785dcff90988261c1c2c72c82dfa3a1ed5b8986b. The commit before (5aaa1a1c0473d9e9ac824201f92ec65e190beeb7) builds successfully:

```
~ % nix build 'github:neovim/neovim/5aaa1a1c0473d9e9ac824201f92ec65e190beeb7?dir=contrib'
~ % ./result/bin/nvim --version
NVIM v0.5.0-dev
Build type: Release
LuaJIT 2.1.0-beta3
Compilation:
Compiled by nixbld
...
```

**Comment by clason** [comment]
Duplicate of #14923 (this is a packaging issue; nothing we can do here).

**Comment by arsham** [comment]
I fixed this by installing the `tree-sitter-git` package from AUR. I had to change the `PKGBUILD` file and add `cargo update` before the `cargo build --release --locked --all-features` line in the `build()` function.

On one of my machine this step worked, on a second machine I had to go into the `src/tree-sitter-git` folder and run make, then into the `cli` folder and run `cargo update && cargo build --release --locked --all-features`, finally ran `makepkg -si` in the root to make it work.

If you find yourself in a situation that these steps fails, you need to run `make clean` otherwise the cached objects might prevent the build to complete.

On both cases after upgrading tree-sitter, building `neovim` from AUR was successful.

I hope it helps.
