### ISSUE TITLE
Compilation error from recent IWYU commit

### ISSUE THREAD

**Issue by jdrouhard** [neovim/neovim#31704]
### Problem

Recent IWYU change (2a7d0ed6145bf3f8b139c2694563f460f829813a) removed `#include <unistd.h>` (in favor of `termios.h`) from non-windows builds. The termios.h file provided by my glibc version (2.28 which is the default for RHEL8) does not include `unistd.h` and is therefore missing `_POSIX_VDISABLE`:

```
/data/source/neovim/src/nvim/tui/termkey/termkey.c: In function 'termkey_start':
/data/source/neovim/src/nvim/tui/termkey/termkey.c:516:31: error: '_POSIX_VDISABLE' undeclared (first use in this function)
  516 |         termios.c_cc[VQUIT] = _POSIX_VDISABLE;
      |                               ^~~~~~~~~~~~~~~
/data/source/neovim/src/nvim/tui/termkey/termkey.c:516:31: note: each undeclared identifier is reported only once for each function it appears in
```

Adding back `#include <unistd.h>` to the top of `termkey.c` provides `_POSIX_VDISABLE` and fixes the compilation error.

### Steps to reproduce

Compile on a system still using glibc 2.28, such as anything based on RHEL8.

### Expected behavior

compiles

### Nvim version (nvim -v)

HEAD

### Vim (not Nvim) behaves the same?

N/A

### Operating system/version

RHEL 8

### Terminal name/version

N/A

### $TERM environment variable

N/A

### Installation

build from repo

**Comment by justinmk** [comment]
Thanks for pointing that out. Fixed in https://github.com/neovim/neovim/pull/31705
