### ISSUE TITLE
Latest git master doesn't build on Mageia Cauldron

### ISSUE THREAD

**Issue by kekePower** [neovim/neovim#19611]
### Neovim version (nvim -v)

git master

### Vim (not Nvim) behaves the same?

N/A

### Operating system/version

Mageia Cauldron x86_64

### Terminal name/version

kitty

### $TERM environment variable

xterm-kitty

### Installation

git master

### How to reproduce the issue

When trying to build using gcc 12.1.1 I get this message and since I'm not a programmer I am unable to try anything.

```shell
[321/374] Building C object src/nvim/CMakeFiles/nvim.dir/terminal.c.o
FAILED: src/nvim/CMakeFiles/nvim.dir/terminal.c.o 
/usr/bin/cc -DINCLUDE_GENERATED_DECLARATIONS -DMIN_LOG_LEVEL=3 -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -D_GNU_SOURCE -Dnvim_EXPORTS -I/projects/neovim/build/cmake.config -I/projects/neovim/src -I/projects/neovim/build/src/nvim/auto -I/projects/neovim/build/include -I/projects/neovim/.deps/usr/include/luajit-2.1 -isystem /projects/neovim/.deps/usr/include -DNVIM_TS_HAS_SET_MATCH_LIMIT -DNVIM_TS_HAS_SET_ALLOCATOR -O2 -DNDEBUG -flto=auto -fno-fat-lto-objects -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wdouble-promotion -Wmissing-noreturn -Wmissing-format-attribute -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=always -MD -MT src/nvim/CMakeFiles/nvim.dir/terminal.c.o -MF src/nvim/CMakeFiles/nvim.dir/terminal.c.o.d -o src/nvim/CMakeFiles/nvim.dir/terminal.c.o -c /projects/neovim/src/nvim/terminal.c
/projects/neovim/src/nvim/terminal.c: In function ‘term_settermprop’:
/projects/neovim/src/nvim/terminal.c:868:40: error: request for member ‘str’ in something not a structure or union
  868 |     buf_set_term_title(buf, val->string.str);
      |                                        ^
[354/374] Building C object src/nvim/CMakeFiles/nvim.dir/viml/parser/expressions.c.o
ninja: build stopped: subcommand failed.
```

Please let me know if you need more information.

### Expected behavior

Would like it to complete the compilation.

### Actual behavior

Compilation aborted.

**Comment by clason** [comment]
Duplicate of #17716 (even though the error message is now slightly different)
