### PR TITLE
[RFC] Fix be64toh() detection on BSDs.

### LINKED ISSUE #4750: Build failure with clang-3.4.1
- Neovim version:0.1.4
- Operating system/version: FreeBSD 10
- Terminal name/version:
- `$TERM`:

fails to build with clang-3.4.1:

```
/usr/ports/editors/neovim/work/neovim-0.1.4/src/nvim/shada.c:3232:32: warning: type specifier missing, defaults to 'int' [-Wimplicit-int]
static inline uint64_t be64toh(uint64_t big_endian_64_bits)
                       ~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/include/sys/endian.h:77:29: note: expanded from macro 'be64toh'
#define be64toh(x)      bswap64((x))
                                 ^
/usr/include/sys/endian.h:61:30: note: expanded from macro 'bswap64'
#define bswap64(x)      __bswap64(x)
                                  ^
/usr/include/x86/endian.h:80:24: note: expanded from macro '__bswap64'
        (__builtin_constant_p(x) ?      \
                              ^
/usr/ports/editors/neovim/work/neovim-0.1.4/src/nvim/shada.c:3232:24: error: expected ')'
static inline uint64_t be64toh(uint64_t big_endian_64_bits)
                       ^
/usr/include/sys/endian.h:77:20: note: expanded from macro 'be64toh'
#define be64toh(x)      bswap64((x))
                        ^
/usr/include/sys/endian.h:61:20: note: expanded from macro 'bswap64'
#define bswap64(x)      __bswap64(x)
                        ^
/usr/include/x86/endian.h:80:27: note: expanded from macro '__bswap64'
        (__builtin_constant_p(x) ?      \
                                 ^
/usr/ports/editors/neovim/work/neovim-0.1.4/src/nvim/shada.c:3232:24: note: to match this '('
/usr/include/sys/endian.h:77:20: note: expanded from macro 'be64toh'
#define be64toh(x)      bswap64((x))
                        ^
/usr/include/sys/endian.h:61:20: note: expanded from macro 'bswap64'
#define bswap64(x)      __bswap64(x)
                        ^
/usr/include/x86/endian.h:80:2: note: expanded from macro '__bswap64'
        (__builtin_constant_p(x) ?      \
        ^
/usr/ports/editors/neovim/work/neovim-0.1.4/src/nvim/shada.c:3232:24: error: static declaration of '__builtin_constant_p' follows non-static declaration
static inline uint64_t be64toh(uint64_t big_endian_64_bits)
                       ^
/usr/include/sys/endian.h:77:20: note: expanded from macro 'be64toh'
#define be64toh(x)      bswap64((x))
                        ^
/usr/include/sys/endian.h:61:20: note: expanded from macro 'bswap64'
#define bswap64(x)      __bswap64(x)
                        ^
/usr/include/x86/endian.h:80:3: note: expanded from macro '__bswap64'
        (__builtin_constant_p(x) ?      \
         ^
/usr/local/include/msgpack/pack_template.h:280:20: note: previous implicit declaration is here
    buf[0] = 0xcd; _msgpack_store16(&buf[1], d);
                   ^
/usr/local/include/msgpack/sysdep.h:156:25: note: expanded from macro '_msgpack_store16'
    do { uint16_t val = _msgpack_be16(num); memcpy(to, &val, 2); } while(0)
                        ^
/usr/local/include/msgpack/sysdep.h:94:34: note: expanded from macro '_msgpack_be16'
#        define _msgpack_be16(x) ntohs(x)
                                 ^
/usr/include/arpa/inet.h:173:18: note: expanded from macro 'ntohs'
#define ntohs(x)        __ntohs(x)
                        ^
/usr/include/x86/endian.h:129:20: note: expanded from macro '__ntohs'
#define __ntohs(x)      __bswap16(x)
                        ^
/usr/include/x86/endian.h:74:16: note: expanded from macro '__bswap16'
        ((__uint16_t)(__builtin_constant_p(x) ? \
                      ^
/usr/ports/editors/neovim/work/neovim-0.1.4/src/nvim/shada.c:3232:24: error: definition of builtin function '__builtin_constant_p'
static inline uint64_t be64toh(uint64_t big_endian_64_bits)
                       ^
/usr/include/sys/endian.h:77:20: note: expanded from macro 'be64toh'
#define be64toh(x)      bswap64((x))
                        ^
/usr/include/sys/endian.h:61:20: note: expanded from macro 'bswap64'
#define bswap64(x)      __bswap64(x)
                        ^
/usr/include/x86/endian.h:80:3: note: expanded from macro '__bswap64'
        (__builtin_constant_p(x) ?      \
         ^
/usr/ports/editors/neovim/work/neovim-0.1.4/src/nvim/shada.c:3232:32: error: parameter name omitted
static inline uint64_t be64toh(uint64_t big_endian_64_bits)
                               ^
/usr/include/sys/endian.h:77:29: note: expanded from macro 'be64toh'
#define be64toh(x)      bswap64((x))
                                 ^
/usr/include/sys/endian.h:61:30: note: expanded from macro 'bswap64'
#define bswap64(x)      __bswap64(x)
                                  ^
/usr/include/x86/endian.h:80:24: note: expanded from macro '__bswap64'
        (__builtin_constant_p(x) ?      \
                              ^
/usr/ports/editors/neovim/work/neovim-0.1.4/src/nvim/shada.c:3240:31: error: use of undeclared identifier 'big_endian_64_bits'
  uint8_t *buf = (uint8_t *) &big_endian_64_bits;
                              ^
1 warning and 5 errors generated.
ninja: build stopped: subcommand failed.
===> Compilation failed unexpectedly.
Try to set MAKE_JOBS_UNSAFE=yes and rebuild before reporting the failure to
the maintainer.
*** Error code 1

Stop.
make: stopped in /usr/ports/editors/neovim
```

### PR DESCRIPTION
**Pull request by jszakmeister**
This was noticed due to a user issue (#4750) when building Neovim 0.1.4
via ports.  The crux of the issue is that we did not detect the
be64toh() macro, because there is no endian.h on FreeBSD (along with
several other BSDs).  So we were defaulting to our builtin version of
be64toh().  However, it appears that sys/endian.h was being picked up by
an include (likely msgpack.h) and so be64toh() was actually defined and
corrupting our definition of it.

So the answer here was to use the correct include file in our check, and
export that information in the config.h.  Then we use that information
to include the right header in shada.c.

This fixes #4750.

### CODE REVIEW

File: config/CMakeLists.txt [hunk 1]
```diff
@@ -67,14 +67,25 @@ if(HAVE_LANGINFO_H)
...
+check_include_files("endian.h" HAVE_ENDIAN_H)
+check_include_files("sys/endian.h" HAVE_SYS_ENDIAN_H)
+
+if(HAVE_ENDIAN_H)
+  set(ENDIAN_INCLUDE_FILE "endian.h")
+elseif(HAVE_SYS_ENDIAN_H)
+  set(ENDIAN_INCLUDE_FILE "sys/endian.h")
+else()
+  set(ENDIAN_INCLUDE_FILE "endian.h")
+endif()
```
Comment (ZyX-I) [inline config/CMakeLists.txt]: It would be more logical to write as

    set(ENDIAN_INCLUDE_FILE "endian.h")
    if(HAVE_SYS_ENDIAN_H)
      if(NOT HAVE_ENDIAN_H)
        set(ENDIAN_INCLUDE_FILE "sys/endian.h")
      endif()
    endif()

(maybe conditions may be joined like `HAVE_SYS_ENDIAN_H AND NOT HAVE_ENDIAN_H`, but I am not sure when this works and when not).

File: config/config.h.in [hunk 2]
```diff
@@ -57,5 +57,7 @@
 
 #cmakedefine HAVE_BE64TOH
 #cmakedefine ORDER_BIG_ENDIAN
+#cmakedefine HAVE_ENDIAN_H
+#cmakedefine HAVE_SYS_ENDIAN_H
```
Comment (ZyX-I) [inline config/config.h.in]: Maybe better `#define ENDIAN_INCLUDE_FILE <@ENDIAN_INCLUDE_FILE@>` and `# include ENDIAN_INCLUDE_FILE` in `shada.c`?

File: config/CMakeLists.txt (hunk 1 above)
Comment (jszakmeister) [inline config/CMakeLists.txt]: I like it.  I'll update with it.

File: config/config.h.in (hunk 2 above)
Comment (jszakmeister) [inline config/config.h.in]: I almost did that this morning... I'll switch it.
