### ISSUE TITLE
Can't run nvim on macOS (10.11.6)

### ISSUE THREAD

**Issue by julien** [neovim/neovim#8524]
- `nvim --version`: Can't be executed because nvim doesn't run on Mac OS 10.11.6
- Vim (version: ) behaves differently? Vim (MacVim in this case) works on Mac OS 10.11.6
- Operating system/version: Mac OS X 10.11.6
- Terminal name/version:
- `$TERM`:  xterm-256color # (Terminal.app)

### Steps to reproduce using `nvim -u NORC`

```
nvim -u NORC

```

### Actual behaviour

nvim-osx64 $ ./bin/nvim 
dyld: Symbol not found: __os_activity_current
  Referenced from: /Users/foobar/nvim-osx64/./bin/../libs/CoreFoundation (which was built for Mac OS X 10.12)
  Expected in: /usr/lib/libSystem.B.dylib
 in /Users/foobar/nvim-osx64/./bin/../libs/CoreFoundation
Trace/BPT trap: 5

### Expected behaviour

edit some files and go home

**Comment by KillTheMule** [comment]
You'll need to tell us how you installed it :)

**Comment by KillTheMule** [comment]
> 1 - I downloaded it from the releases page

So in that case can we assume you downloaded 0.3? Not trying to be obstinate, just wanting to make sure so that someone else has all the info needed.

**Comment by julien** [comment]
@KillTheMule, yes, I downloaded `0.3.0` from [here](https://github.com/neovim/neovim/releases/download/v0.3.0/nvim-macos.tar.gz)

**Comment by justinmk** [comment]
This is because travis changed its macOS env default to 10.12. 

https://docs.travis-ci.com/user/reference/osx/#OS-X-Version

We can see if [bot-ci](https://github.com/neovim/bot-ci) will work with 10.10 or 10.11.

In the meantime @julien Neovim is available via homebrew, assuming homebrew still supports 10.11.

**Comment by julien** [comment]
@justinmk Ok thanks for the explanation.
I guess we can close this one then.

**Comment by E5ten** [comment]
I think this should be reopened until we see if bot-ci can work with 10.10/10.11, if it can obviously it should be closed, and if it can't there's nothing that can be done so it can be closed. As of now though the issue is still relevant.

**Comment by julien** [comment]
@E5ten reopened

**Comment by jamessan** [comment]
According to [Travis' docs](https://docs.travis-ci.com/user/reference/osx/#OS-X-Version), these are the available macOS versions:

osx_image value | Xcode version | OS X version | JDK
-- | -- | -- | --
osx_image: xcode9.3 | Xcode 9.3 | OS X 10.13 | 1.8.0_112-b16
osx_image: xcode9.2 | Xcode 9.2 | OS X 10.12 | 1.8.0_112-b16
osx_image: xcode9.1 | Xcode 9.1 | OS X 10.12 | 1.8.0_112-b16
osx_image: xcode9 | Xcode 9 | OS X 10.12 | 1.8.0_112-b16
osx_image: xcode8.3  Default | Xcode 8.3.3 | OS X 10.12 | 1.8.0_112-b16
osx_image: xcode8 | Xcode 8gm | OS X 10.11 | 1.8.0_92-b14
osx_image: xcode7.3 | Xcode 7.3.1 | OS X 10.11 | 1.8.0_92-b14
osx_image: xcode6.4 | Xcode 6.4 | OS X 10.10 | 1.8.0_45-b14

We can go back to `osx_image: xcode6.4` to support 10.10, however I don't know if that has implications on supporting newer macOS versions.

**Comment by jamessan** [comment]
Hmm, our [travis config](https://github.com/neovim/neovim/blob/463da8480685dbd53335b4e3f0a6d37cacbacac4/.travis.yml) is using `osx_image: xcode7.3` so it should work with macOS 10.11.  However [bot-ci's travis config](https://github.com/neovim/bot-ci/blob/be607c7035e112afae048aee2e06edadce8a7f65/.travis.yml) is using the default image.  These need to be kept in sync.

**Comment by jamessan** [comment]
neovim/bot-ci#132 will update the travis config so it matches what we use in this repo.

**Comment by jamessan** [comment]
The bot-ci PR has been merged, so nightly builds should be usable again once that job finishes.
