### PR TITLE
feat(lsp): support vim.lsp.ListOpts for typehierarchy()

### PR DESCRIPTION
**Pull request by tom-anders**

### CODE REVIEW

File: runtime/lua/vim/lsp/handlers.lua [hunk 1]
```diff
@@ -593,8 +593,19 @@ local function make_type_hierarchy_handler()
...
+    if config.loclist then
+      vim.fn.setloclist(0, {}, ' ', { title = title, items = items, context = ctx })
+      api.nvim_command('lopen')
+    elseif config.on_list then
+      assert(type(config.on_list) == 'function', 'on_list is not a function')
+      config.on_list({ title = title, items = items, context = ctx })
+    else
+      vim.fn.setqflist({}, ' ', { title = title, items = items, context = ctx })
+      api.nvim_command('botright copen')
+    end
```
Comment (MariaSolOs) [inline runtime/lua/vim/lsp/handlers.lua:608]: You can even make the entire table a shared variable:
```suggestion
    config = config or {}
    local list = { title = 'LSP type hierarchy', items = items, context = ctx }

    if config.loclist then
      vim.fn.setloclist(0, {}, ' ', list)
      api.nvim_command('lopen')
    elseif config.on_list then
      assert(type(config.on_list) == 'function', 'on_list is not a function')
      config.on_list(list)
    else
      vim.fn.setqflist({}, ' ', list)
      api.nvim_command('botright copen')
    end
```

File: runtime/doc/lsp.txt [hunk 2]
```diff
@@ -1437,13 +1437,14 @@ type_definition({options})                     *vim.lsp.buf.type_definition()*
     Parameters: ~
       • {options}  (`vim.lsp.LocationOpts?`) See |vim.lsp.LocationOpts|.
 
-typehierarchy({kind})                            *vim.lsp.buf.typehierarchy()*
+typehierarchy({kind}, {options})                 *vim.lsp.buf.typehierarchy()*
```
[the remark this answers is not in the document]
Comment (tom-anders) [reply runtime/doc/lsp.txt:1440]: Ah right, I basically `vim.lsp.buf.references()` also calls this `options` instead of `opts`, we should probably change that as well then?

**Comment by tom-anders** [comment]
Thanks for the review!

File: runtime/doc/lsp.txt (hunk 2 above)
[the remark this answers is not in the document]
Comment (justinmk) [reply runtime/doc/lsp.txt]: > I basically copied this from `vim.lsp.buf.references()` which also calls this `options` instead of `opts`, we should probably change that as well then?

yes. shorter is better. and "options" means something very different in vim/nvim.

[the remark this answers is not in the document]
Comment (tom-anders) [reply runtime/doc/lsp.txt]: Right, I added an additional commit that fixes this for all other functions in buf.lua

File: runtime/doc/lsp.txt [hunk 3]
```diff
@@ -1245,30 +1245,30 @@ add_workspace_folder({workspace_folder})
 clear_references()                            *vim.lsp.buf.clear_references()*
     Removes document highlights from current buffer.
 
-code_action({options})                             *vim.lsp.buf.code_action()*
+code_action({opts})                                *vim.lsp.buf.code_action()*
```
Comment (MariaSolOs) [inline runtime/doc/lsp.txt:1248]: Maybe its something with my browser, but there seems to be some trailing whitespace here (?). Assuming you didn't modify these files manually and instead ran `make doc`, this might be a bug in the doc generator (cc @lewis6991)

Comment (zeertzjq) [reply runtime/doc/lsp.txt:1248]: More whitespace is needed to align the tags.

Comment (MariaSolOs) [reply runtime/doc/lsp.txt:1248]: Oh duh. In that case ignore my comment lol.

**Comment by tom-anders** [comment]
Latest push fixes the lua warning about a shadowed parameter. Is there any way to disable the next.txt check? Or do we just ignore it?

**Comment by glepnir** [comment]
news for *feat* change scope will skip it.

**Comment by tom-anders** [comment]
> news for _feat_ change scope will skip it.

Right, but I think `feat` is appropiate here, isn't it? Or should this be a `fix` instead?

File: runtime/lua/vim/lsp/handlers.lua [hunk 4]
```diff
@@ -593,8 +593,19 @@ local function make_type_hierarchy_handler()
...
+      vim.fn.setloclist(0, {}, ' ', list)
+      api.nvim_command('lopen')
+    elseif config.on_list then
+      assert(type(config.on_list) == 'function', 'on_list is not a function')
+      config.on_list(list)
+    else
+      vim.fn.setqflist({}, ' ', list)
+      api.nvim_command('botright copen')
+    end
   end
```
Comment (justinmk) [inline runtime/lua/vim/lsp/handlers.lua:609]: is there a test that at least exercises most of this?

File: runtime/lua/vim/lsp/buf.lua [hunk 5]
```diff
@@ -47,6 +47,16 @@ local function request_with_options(name, params, options)
   request(name, params, req_handler)
 end
 
+local function client_request_with_options(client, name, params, options, bufnr)
```
Comment (justinmk) [inline runtime/lua/vim/lsp/buf.lua:50]: don't repeat parameters in the name, unless it is truly necessary to disambiguate from some other local function. the docstring should be enough (which this currently lacks)

```suggestion
--- Calls client.request with the given `opts`.
local function client_request(client, name, params, opts, bufnr)
```

File: runtime/lua/vim/lsp/handlers.lua [hunk 6]
```diff
@@ -593,8 +593,19 @@ local function make_type_hierarchy_handler()
...
       })
     end
-    vim.fn.setqflist({}, ' ', { title = 'LSP type hierarchy', items = items })
-    api.nvim_command('botright copen')
+    config = config or {}
+    local list = { title = 'LSP type hierarchy', items = items, context = ctx }
+
+    if config.loclist then
+      vim.fn.setloclist(0, {}, ' ', list)
+      api.nvim_command('lopen')
```
Comment (lewis6991) [inline runtime/lua/vim/lsp/handlers.lua:601]:
```suggestion
      vim.cmd.lopen()
```

File: runtime/lua/vim/lsp/handlers.lua [hunk 7]
```diff
@@ -593,8 +593,19 @@ local function make_type_hierarchy_handler()
...
+    elseif config.on_list then
+      assert(type(config.on_list) == 'function', 'on_list is not a function')
+      config.on_list(list)
+    else
+      vim.fn.setqflist({}, ' ', list)
+      api.nvim_command('botright copen')
```
Comment (lewis6991) [inline runtime/lua/vim/lsp/handlers.lua:607]:
```suggestion
      vim.cmd('botright copen')
```

**Comment by tom-anders** [comment]
Thanks for the review again!

I noticed that the `loclist` key to `vim.lsp.ListOpts` is not actually documented, but most LSP handlers still support it (e.g. references, documentSymbols, workspaceSymbol). There are some LSP handlers though that do not support it (declaration, definition, typeDefinition, implementation). Should I fix this in this PR as well, or maybe open a new one instead?

File: runtime/lua/vim/lsp/handlers.lua [hunk 8]
```diff
@@ -593,8 +593,19 @@ local function make_type_hierarchy_handler()
...
-    vim.fn.setqflist({}, ' ', { title = 'LSP type hierarchy', items = items })
-    api.nvim_command('botright copen')
+    config = config or {}
+    local list = { title = 'LSP type hierarchy', items = items, context = ctx }
+
+    if config.loclist then
+      vim.fn.setloclist(0, {}, ' ', list)
+      vim.cmd.lopen()
+    elseif config.on_list then
+      assert(type(config.on_list) == 'function', 'on_list is not a function')
```
Comment (wookayin) [inline runtime/lua/vim/lsp/handlers.lua:603]: Please consider using `vim.is_callable()` instead.

**Comment by tom-anders** [comment]
All suggestions should be applied now, I moved the cleanup to a new PR: #28637

File: test/functional/plugin/lsp_spec.lua [hunk 9]
```diff
@@ -3597,6 +3597,94 @@ describe('LSP', function()
       eq(expected, qflist)
     end)
 
+    it('Opens the loclist if config contains `loclist`', function()
+      clear()
```
Comment (MariaSolOs) [inline test/functional/plugin/lsp_spec.lua:3601]: I don't think this `clear` is needed since the `before_each` test function already calls it.

File: runtime/lua/vim/lsp/handlers.lua (hunk 7 above)
Comment (famiu) [reply runtime/lua/vim/lsp/handlers.lua]: `vim.cmd.botright('copen')` would be better, no?

Comment (zeertzjq) [reply runtime/lua/vim/lsp/handlers.lua]: `vim.cmd.copen({ mods = { split = 'botright' } })`

Comment (tom-anders) [reply runtime/lua/vim/lsp/handlers.lua]: @zeertzjq done :)

**Comment by tom-anders** [comment]
(rebased to fix conflicts caused by #28637)

File: runtime/lua/vim/lsp/buf.lua [hunk 10]
```diff
@@ -47,6 +47,17 @@ local function request_with_opts(name, params, opts)
   request(name, params, req_handler)
 end
 
+--- Calls client.request with the given `opts`.
+local function client_request_with_options(client, name, params, opts, bufnr)
```
Comment (justinmk) [inline runtime/lua/vim/lsp/buf.lua:51]: is this different from `request_with_opts` which was merged in https://github.com/neovim/neovim/pull/28637 ?
