### ISSUE TITLE
Ubuntu 14.10 Build Fails

### ISSUE THREAD

**Issue by rustushki** [neovim/neovim#2052]
When I try to build in Ubuntu 14.10, I'm receiving a build error:

/usr/bin/ld: ../../../../.deps/usr/lib/libuv.a(libuv_la-thread.o): undefined reference to symbol 'pthread_rwlock_trywrlock@@GLIBC_2.2.5'
/lib/x86_64-linux-gnu/libpthread.so.0: error adding symbols: DSO missing from command line

Here's a link to the full build:
https://gist.github.com/rustushki/7555d178690e1c152f7a

**Comment by fwalch** [comment]
See also https://github.com/neovim/neovim/pull/2037#issuecomment-75753401.

**Comment by cacplate** [comment]
Archlinux 64bit doesn't compile with the same error.

**Comment by rainerborene** [comment]
> Archlinux 64bit doesn't compile with the same error.

Same here.

**Comment by jszakmeister** [comment]
Can you try #2053 and/or #2054?

**Comment by jalvesaq** [comment]
I am using Ubuntu 14.10. I did not test https://github.com/neovim/neovim/pull/2053, but I tested https://github.com/neovim/neovim/pull/2054 and it solves the compilation bug.

To test the pull request, I did the following:

```
git remote add jsz https://github.com/jszakmeister/neovim.git
git fetch jsz
git checkout jsz/fix-tty-test-link 
make
sudo make install
```

**Comment by Numkil** [comment]
Fedora 21 also has the same error on build. #2054 solves the problem for me as well.

**Comment by raichoo** [comment]
Same problem on Arch Linux as well.

**Comment by renstrom** [comment]
Had this problem on CentOS 7, and https://github.com/neovim/neovim/pull/2054 fixed the issue there as well.

**Comment by raichoo** [comment]
Ah, didn't see there was a pending fix. Indeed #2054 fixes it.

**Comment by jszakmeister** [comment]
#2053 should fix this as well and has been merged to master.  Can one of you verify that master now works for you?

**Comment by lordi** [comment]
Master now compiles fine on Arch Linux

**Comment by jszakmeister** [comment]
@jalvesaq An easier way to fetch a pull request is to use the `refs/pull` namespace available on GitHub repos:

```text
git fetch origin pull/2054/head:pr-2054
```

The above would pull the tip of the PR into a branch named pr-2054.  In fact, this is so handy that I have a [little script](/jszakmeister/etc/blob/master/git-addons/git-fetch-pull-request) to help me do it.  The script will check for the presence of a remote called "upstream" which it will use as the main repo, or fallback to "origin" if "upstream" is not present.  Then it will pull the specified pr numbers into branches for you.  I've aliased `fpr` as `fetch-pull-request` to make it even simpler to use. :-)

**Comment by jalvesaq** [comment]
@jszakmeister Thanks for the explanation!

The master branch is compiling fine in Ubuntu 14.10 (64bit).

**Comment by rustushki** [comment]
@jalvesaq @jszakmeister I can confirm the same.  Many thanks.

**Comment by jszakmeister** [comment]
Great!  I'm closing this ticket now that it's all fixed. :-)  Thanks for all the help!
