### ISSUE TITLE
homebrew --HEAD fails to build

### ISSUE THREAD

**Issue by cvlmtg** [neovim/neovim#10991]
`brew install --HEAD nvim` produces the following error:

```
==> luarocks make --lua-dir=/usr/local/opt/luajit --tree=/private/tmp/neovim-20
==> cmake . -DCMAKE_C_FLAGS_RELEASE=-DNDEBUG -DCMAKE_CXX_FLAGS_RELEASE=-DNDEBUG
==> make install
==> cmake .. -DCMAKE_C_FLAGS_RELEASE=-DNDEBUG -DCMAKE_CXX_FLAGS_RELEASE=-DNDEBU
==> make install
Last 15 lines from /Users/matteo/Library/Logs/Homebrew/neovim/07.make:
                                              ~~~~~ ^
/tmp/neovim-20190911-11845-1estqth/src/nvim/macros.h:154:47: note: expanded from macro 'RGB_'
#define RGB_(r, g, b) ((r << 16) | (g << 8) | b)
                                              ^
/tmp/neovim-20190911-11845-1estqth/src/nvim/terminal.c:601:32: error: no member named 'indexed' in 'VTermColor'
                     ? cell.fg.indexed.idx + 1 : 0);
                       ~~~~~~~ ^
/tmp/neovim-20190911-11845-1estqth/src/nvim/terminal.c:603:32: error: no member named 'indexed' in 'VTermColor'
                     ? cell.bg.indexed.idx + 1 : 0);
                       ~~~~~~~ ^
5 errors generated.
make[2]: *** [src/nvim/CMakeFiles/nvim.dir/terminal.c.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[1]: *** [src/nvim/CMakeFiles/nvim.dir/all] Error 2
make: *** [all] Error 2
```

this is a more complete stacktrace of the error:

```
cd /tmp/neovim-20190911-11845-1estqth/build/src/nvim && /usr/local/Homebrew/Library/Homebrew/shims/mac/super
/clang -DINCLUDE_GENERATED_DECLARATIONS -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -D_GNU_SOURCE -
I/tmp/neovim-20190911-11845-1estqth/build/config -I/tmp/neovim-20190911-11845-1estqth/src -I/tmp/neovim-2019
0911-11845-1estqth/build/src/nvim/auto -I/tmp/neovim-20190911-11845-1estqth/build/include -I/usr/local/inclu
de/luajit-2.0 -isystem /tmp/neovim-20190911-11845-1estqth/deps-build/include -isystem /Library/Developer/Com
mandLineTools/SDKs/MacOSX10.14.sdk/usr/include  -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNDEBUG -DMIN_LOG_LEV
EL=3 -flto=thin -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk   -Wall -Wextra -pedantic
 -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-
fallthrough -Wvla -fstack-protector-strong -fdiagnostics-color=auto -o CMakeFiles/nvim.dir/tui/input.c.o   -
c /tmp/neovim-20190911-11845-1estqth/src/nvim/tui/input.c
/tmp/neovim-20190911-11845-1estqth/src/nvim/terminal.c:572:21: error: no member named 'rgb' in 'VTermColor'
  return RGB_(color.rgb.red, color.rgb.green, color.rgb.blue);
              ~~~~~ ^
/tmp/neovim-20190911-11845-1estqth/src/nvim/macros.h:154:25: note: expanded from macro 'RGB_'
#define RGB_(r, g, b) ((r << 16) | (g << 8) | b)
                        ^
/tmp/neovim-20190911-11845-1estqth/src/nvim/terminal.c:572:36: error: no member named 'rgb' in 'VTermColor'
  return RGB_(color.rgb.red, color.rgb.green, color.rgb.blue);
                             ~~~~~ ^
/tmp/neovim-20190911-11845-1estqth/src/nvim/macros.h:154:37: note: expanded from macro 'RGB_'
#define RGB_(r, g, b) ((r << 16) | (g << 8) | b)
                                    ^
/tmp/neovim-20190911-11845-1estqth/src/nvim/terminal.c:572:53: error: no member named 'rgb' in 'VTermColor'
  return RGB_(color.rgb.red, color.rgb.green, color.rgb.blue);
                                              ~~~~~ ^
/tmp/neovim-20190911-11845-1estqth/src/nvim/macros.h:154:47: note: expanded from macro 'RGB_'
#define RGB_(r, g, b) ((r << 16) | (g << 8) | b)
                                              ^
/tmp/neovim-20190911-11845-1estqth/src/nvim/terminal.c:601:32: error: no member named 'indexed' in 'VTermCol
or'
                     ? cell.fg.indexed.idx + 1 : 0);
                       ~~~~~~~ ^
/tmp/neovim-20190911-11845-1estqth/src/nvim/terminal.c:603:32: error: no member named 'indexed' in 'VTermCol
or'
                     ? cell.bg.indexed.idx + 1 : 0);
                       ~~~~~~~ ^
5 errors generated.
make[2]: *** [src/nvim/CMakeFiles/nvim.dir/terminal.c.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[1]: *** [src/nvim/CMakeFiles/nvim.dir/all] Error 2
make: *** [all] Error 2
```

**Comment by clason** [comment]
The problem seems to be that the formula relies on homebrew's `libvterm`, which has not been updated to v0.1 so far (`brew info` claims `stable 726`). Updating the formula for `libvterm` should fix this.

**Comment by clason** [comment]
@cvlmtg This should be reported at homebrew-core and be pretty easy to fix. The maintainers don't support HEAD builds, so I think you should wait until neovim 0.4.0 is released. 

@justinmk I assume neovim 0.3.8 does not build with libvterm 0.1, so the formula should keep the old version around, and the dependencies of the neovim formula need to be adapted?

**Comment by justinmk** [comment]
> I assume neovim 0.3.8 does not build with libvterm 0.1,

correct

> so the formula should keep the old version around, and the dependencies of the neovim formula need to be adapted?

We're pretty close to an Nvim release , so ...

**Comment by clason** [comment]
See https://github.com/Homebrew/homebrew-core/pull/44318/commits/3c29e07d4024fbc838db804da33f1f1a6621a7bd

**Comment by clason** [comment]
Fixed upstream: https://github.com/Homebrew/homebrew-core/commit/825a94db1fa32aee662fe415937c6d6909808504
